### ISSUE TITLE
Install Relaton NIST fetch workflow to fetch full NIST dataset here

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-data-nist#1]

**Comment by ronaldtse** [comment]
Duplicate relaton/relaton-data-nist setup here.

**Comment by andrew2net** [comment]
@ronaldtse now we have a `relaton fetch-data` command. Can we close this issue?

**Comment by ronaldtse** [comment]
Done, repo created at ietf-ribose/relaton-data-nist is fetching normally now.
