### ISSUE TITLE
Semicolon in filename

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-data-nist#4]
https://github.com/ietf-ribose/bibxml-data-nist/blob/main/data/NBS_REPORT_%3B_2188.xml

This seems like one peculiarly formed standard reference.

**Comment by ronaldtse** [comment]
Yes, and in fact, the identifier is also broken:

```xml
<reference anchor="NIST." target="https://nvlpubs.nist.gov/nistpubs/Legacy/RPT/nbsreport2188.pdf">
  <front>
    <title>Quantum dynamics : part I</title>
    <seriesInfo name="DOI" value="10.6028/NBS.RPT.2188"/>
```

@andrew2net can you please help fix this in relaton-nist? Thanks.

**Comment by ronaldtse** [comment]
This issue is related to the NBS Report type, filed here: https://github.com/relaton/relaton-nist/issues/59

**Comment by strogonoff** [comment]
Related general question: https://github.com/ietf-ribose/bibxml-project/issues/8
